// <auto-generated />
using System;
using ManagerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManagerService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408064008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "document_check_status", new[] { "не_проверен", "отклонён", "утверждён" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "employee_role", new[] { "supervisor", "manager" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "manager_slot_status", new[] { "отменен", "черновик", "подтвержден", "опубликован", "занят" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "practice_format", new[] { "очная", "дистанционная", "гибридная" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "signing_document_status", new[] { "не_подписан", "подписан_университетом", "подписан_ламой", "подписан_всеми" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManagerService.Models.manager.DocumentForSpecialization", b =>
                {
                    b.Property<int>("IdDocumentType")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.HasKey("IdDocumentType", "IdSpecialization");

                    b.HasIndex("IdSpecialization");

                    b.ToTable("DocumentsForSpecialization");
                });

            modelBuilder.Entity("ManagerService.Models.manager.DocumentType", b =>
                {
                    b.Property<int>("IdDocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumentType"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdDocumentType");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("ManagerService.Models.manager.ManagerInterval", b =>
                {
                    b.Property<int>("IdManagerInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdManagerInterval"));

                    b.Property<TimeSpan?>("BreakDuration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("managerIdEmployee")
                        .HasColumnType("integer");

                    b.HasKey("IdManagerInterval");

                    b.HasIndex("managerIdEmployee");

                    b.ToTable("ManagerIntervals");
                });

            modelBuilder.Entity("ManagerService.Models.manager.ManagerInterview", b =>
                {
                    b.Property<int>("IdManagerSlot")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdStudent")
                        .HasColumnType("integer");

                    b.Property<int>("IdStudentApplication")
                        .HasColumnType("integer");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdManagerSlot");

                    b.ToTable("ManagerInterviews");
                });

            modelBuilder.Entity("ManagerService.Models.manager.ManagerSlot", b =>
                {
                    b.Property<int>("IdManagerSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdManagerSlot"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("integer");

                    b.Property<int>("IdManagerInterval")
                        .HasColumnType("integer");

                    b.Property<string>("MeetingPlace")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("manager_slot_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdManagerSlot");

                    b.HasIndex("IdManagerInterval");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("ManagerSlots");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdAddress");

                    b.HasIndex("IdDepartment");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Department", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartment"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdDepartment");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmployee"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PersonnelNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("employee_role");

                    b.HasKey("IdEmployee");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdDepartment");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PersonnelNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ManagerService.Models.shared.PracticeType", b =>
                {
                    b.Property<int>("IdPracticeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPracticeType"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdPracticeType");

                    b.ToTable("PracticeTypes");
                });

            modelBuilder.Entity("ManagerService.Models.shared.ScheduledPractice", b =>
                {
                    b.Property<int>("IdScheduledPractice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdScheduledPractice"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPracticeType")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdScheduledPractice");

                    b.HasIndex("IdPracticeType");

                    b.HasIndex("IdSpecialization");

                    b.ToTable("ScheduledPractices");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Specialization", b =>
                {
                    b.Property<int>("IdSpecialization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSpecialization"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdSpecialization");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("ManagerService.Models.manager.DocumentForSpecialization", b =>
                {
                    b.HasOne("ManagerService.Models.manager.DocumentType", "DocumentType")
                        .WithMany("DocumentForSpecialization")
                        .HasForeignKey("IdDocumentType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagerService.Models.shared.Specialization", "Specialization")
                        .WithMany("DocumentForSpecialization")
                        .HasForeignKey("IdSpecialization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ManagerService.Models.manager.ManagerInterval", b =>
                {
                    b.HasOne("ManagerService.Models.shared.Employee", "manager")
                        .WithMany()
                        .HasForeignKey("managerIdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("manager");
                });

            modelBuilder.Entity("ManagerService.Models.manager.ManagerInterview", b =>
                {
                    b.HasOne("ManagerService.Models.manager.ManagerSlot", "ManagerSlot")
                        .WithOne("ManagerInterview")
                        .HasForeignKey("ManagerService.Models.manager.ManagerInterview", "IdManagerSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerSlot");
                });

            modelBuilder.Entity("ManagerService.Models.manager.ManagerSlot", b =>
                {
                    b.HasOne("ManagerService.Models.manager.ManagerInterval", "ManagerInterval")
                        .WithMany("ManagerSlots")
                        .HasForeignKey("IdManagerInterval")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagerInterval");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Address", b =>
                {
                    b.HasOne("ManagerService.Models.shared.Department", "Department")
                        .WithMany("Addresses")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Employee", b =>
                {
                    b.HasOne("ManagerService.Models.shared.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ManagerService.Models.shared.ScheduledPractice", b =>
                {
                    b.HasOne("ManagerService.Models.shared.PracticeType", "PracticeType")
                        .WithMany("ScheduledPractices")
                        .HasForeignKey("IdPracticeType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagerService.Models.shared.Specialization", "Specialization")
                        .WithMany("ScheduledPractices")
                        .HasForeignKey("IdSpecialization")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeType");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ManagerService.Models.manager.DocumentType", b =>
                {
                    b.Navigation("DocumentForSpecialization");
                });

            modelBuilder.Entity("ManagerService.Models.manager.ManagerInterval", b =>
                {
                    b.Navigation("ManagerSlots");
                });

            modelBuilder.Entity("ManagerService.Models.manager.ManagerSlot", b =>
                {
                    b.Navigation("ManagerInterview");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Department", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ManagerService.Models.shared.PracticeType", b =>
                {
                    b.Navigation("ScheduledPractices");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Specialization", b =>
                {
                    b.Navigation("DocumentForSpecialization");

                    b.Navigation("ScheduledPractices");
                });
#pragma warning restore 612, 618
        }
    }
}
