// <auto-generated />
using System;
using ManagerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManagerService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404131703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "document_check_status", new[] { "не_проверен", "отклонён", "утверждён" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "employee_role", new[] { "supervisor", "manager" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "interview_slot_status", new[] { "отменен", "черновик", "предложен_руководителю", "подтвержден", "опубликован", "занят" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "interview_type", new[] { "менеджер", "руководитель" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "practice_format", new[] { "очная", "дистанционная", "гибридная" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "signing_document_status", new[] { "не_подписан", "подписан_университетом", "подписан_ламой", "подписан_всеми" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "student_application_status", new[] { "на_рассмотрении_руководителем", "отказано", "собеседование", "оформление_документов", "принят" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "supervisor_application_status", new[] { "отменена", "шаблон", "отправлена", "удовлетворена", "неудовлетворена", "закрыта" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.Property<int>("IdInterviewSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInterviewSlot"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uuid");

                    b.Property<int>("IdInterval")
                        .HasColumnType("integer");

                    b.Property<string>("MeetingPlace")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterviewSlot");

                    b.HasIndex("IdInterval");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("InterviewSlots");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.StudentSupervisorApplication", b =>
                {
                    b.Property<Guid>("IdSupervisorApplication")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdStudentApplication")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdSupervisorApplication", "IdStudentApplication");

                    b.ToTable("StudentSupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorApplication", b =>
                {
                    b.Property<Guid>("IdSupervisorApplication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAddress")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdCreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uuid");

                    b.Property<int?>("IdScheduledPractice")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("PracticeFormat")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedStudentsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdSupervisorApplication");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("Status");

                    b.ToTable("SupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorReview", b =>
                {
                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdStudentApplication")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IndependenceScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<int>("PvScore")
                        .HasColumnType("integer");

                    b.Property<bool>("RecommendedForEmployment")
                        .HasColumnType("boolean");

                    b.Property<int>("SkillsScore")
                        .HasColumnType("integer");

                    b.Property<int>("TeamworkScore")
                        .HasColumnType("integer");

                    b.HasKey("IdEmployee", "IdStudentApplication");

                    b.ToTable("SupervisorReviews");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.TimeInterval", b =>
                {
                    b.Property<int>("IdInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInterval"));

                    b.Property<TimeSpan?>("BreakDuration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterval");

                    b.ToTable("TimeIntervals");
                });

            modelBuilder.Entity("ManagerService.Models.Supervisor.Interview", b =>
                {
                    b.Property<int>("IdInterviewSlot")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InterviewType")
                        .HasColumnType("integer");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterviewSlot");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("ManagerService.Models.manager.DocumentForSpecialization", b =>
                {
                    b.Property<int>("IdDocumentType")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.HasKey("IdDocumentType", "IdSpecialization");

                    b.HasIndex("IdSpecialization");

                    b.ToTable("DocumentsForSpecialization");
                });

            modelBuilder.Entity("ManagerService.Models.manager.DocumentType", b =>
                {
                    b.Property<int>("IdDocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumentType"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdDocumentType");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("ManagerService.Models.manager.StudentApplication", b =>
                {
                    b.Property<int>("IdStudentApplication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStudentApplication"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("IdPracticeType")
                        .HasColumnType("integer");

                    b.Property<int>("IdScheduledPractice")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IdStudentApplication");

                    b.HasIndex("IdPracticeType");

                    b.HasIndex("IdScheduledPractice");

                    b.HasIndex("IdSpecialization");

                    b.ToTable("StudentApplications");
                });

            modelBuilder.Entity("ManagerService.Models.manager.StudentDocument", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocument"));

                    b.Property<int>("DocumentCheckStatus")
                        .HasColumnType("integer");

                    b.Property<int>("IdDocumentType")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<int>("IdStudentApplication")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("LoadDate")
                        .HasColumnType("date");

                    b.Property<string>("PathToFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SigningDocumentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("StudentApplication")
                        .HasColumnType("integer");

                    b.Property<bool>("isLoaded")
                        .HasColumnType("boolean");

                    b.HasKey("IdDocument");

                    b.HasIndex("StudentApplication");

                    b.HasIndex("IdDocumentType", "IdSpecialization");

                    b.ToTable("StudentDocuments");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdAddress");

                    b.HasIndex("IdDepartment");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Department", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartment"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdDepartment");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Employee", b =>
                {
                    b.Property<Guid>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PersonnelNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("IdEmployee");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdDepartment");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PersonnelNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ManagerService.Models.shared.PracticeType", b =>
                {
                    b.Property<int>("IdPracticeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPracticeType"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdPracticeType");

                    b.ToTable("PracticeTypes");
                });

            modelBuilder.Entity("ManagerService.Models.shared.ScheduledPractice", b =>
                {
                    b.Property<int>("IdScheduledPractice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdScheduledPractice"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPracticeType")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdScheduledPractice");

                    b.HasIndex("IdPracticeType");

                    b.HasIndex("IdSpecialization");

                    b.ToTable("ScheduledPractices");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Specialization", b =>
                {
                    b.Property<int>("IdSpecialization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSpecialization"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdSpecialization");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.TimeInterval", "TimeInterval")
                        .WithMany("InterviewSlots")
                        .HasForeignKey("IdInterval")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimeInterval");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.StudentSupervisorApplication", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.SupervisorApplication", "SupervisorApplication")
                        .WithMany("StudentSupervisorApplications")
                        .HasForeignKey("IdSupervisorApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupervisorApplication");
                });

            modelBuilder.Entity("ManagerService.Models.Supervisor.Interview", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.InterviewSlot", "InterviewSlot")
                        .WithOne("Interview")
                        .HasForeignKey("ManagerService.Models.Supervisor.Interview", "IdInterviewSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSlot");
                });

            modelBuilder.Entity("ManagerService.Models.manager.DocumentForSpecialization", b =>
                {
                    b.HasOne("ManagerService.Models.manager.DocumentType", null)
                        .WithMany("DocumentForSpecialization")
                        .HasForeignKey("IdDocumentType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagerService.Models.shared.Specialization", null)
                        .WithMany("DocumentForSpecialization")
                        .HasForeignKey("IdSpecialization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManagerService.Models.manager.StudentApplication", b =>
                {
                    b.HasOne("ManagerService.Models.manager.StudentApplication", "PracticeType")
                        .WithMany()
                        .HasForeignKey("IdPracticeType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagerService.Models.manager.StudentApplication", "ScheduledPractice")
                        .WithMany()
                        .HasForeignKey("IdScheduledPractice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagerService.Models.manager.StudentApplication", "Specialization")
                        .WithMany()
                        .HasForeignKey("IdSpecialization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeType");

                    b.Navigation("ScheduledPractice");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ManagerService.Models.manager.StudentDocument", b =>
                {
                    b.HasOne("ManagerService.Models.manager.StudentApplication", "SupervisorApplication")
                        .WithMany()
                        .HasForeignKey("StudentApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagerService.Models.manager.DocumentForSpecialization", "DocumentForSpecialization")
                        .WithMany("StudentDocument")
                        .HasForeignKey("IdDocumentType", "IdSpecialization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentForSpecialization");

                    b.Navigation("SupervisorApplication");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Address", b =>
                {
                    b.HasOne("ManagerService.Models.shared.Department", "Department")
                        .WithMany("Addresses")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Employee", b =>
                {
                    b.HasOne("ManagerService.Models.shared.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ManagerService.Models.shared.ScheduledPractice", b =>
                {
                    b.HasOne("ManagerService.Models.shared.PracticeType", "PracticeType")
                        .WithMany("ScheduledPractices")
                        .HasForeignKey("IdPracticeType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagerService.Models.shared.Specialization", "Specialization")
                        .WithMany("ScheduledPractices")
                        .HasForeignKey("IdSpecialization")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeType");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.Navigation("Interview");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorApplication", b =>
                {
                    b.Navigation("StudentSupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.TimeInterval", b =>
                {
                    b.Navigation("InterviewSlots");
                });

            modelBuilder.Entity("ManagerService.Models.manager.DocumentForSpecialization", b =>
                {
                    b.Navigation("StudentDocument");
                });

            modelBuilder.Entity("ManagerService.Models.manager.DocumentType", b =>
                {
                    b.Navigation("DocumentForSpecialization");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Department", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ManagerService.Models.shared.PracticeType", b =>
                {
                    b.Navigation("ScheduledPractices");
                });

            modelBuilder.Entity("ManagerService.Models.shared.Specialization", b =>
                {
                    b.Navigation("DocumentForSpecialization");

                    b.Navigation("ScheduledPractices");
                });
#pragma warning restore 612, 618
        }
    }
}
